Use same build string glob as python's run_exports
This is to avoid
  ValueError: Incompatible component merge:
    - '*_cpython'
    - '*cpython'
caused by https://github.com/conda/conda/issues/11442 .

Signed-off-by: Marcel Bargull <marcel.bargull@udo.edu>